[package]
name = "CUIBOX"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
cockpit = "0.2.2"
crossterm = "0.28"
ratatui = "0.29"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
